<template>

   <div class=" rounded-lg bg-blue-imbt hover:bg-blue-hov hover:text-white">
      <p class="text-blue-textm hover:text-white text-base px-6 py-8 "><span class="font-semibold text-2xl pb-4">Easiest and Fast</span>
      <br>We stand up for the right of everyone to <br> be equal </p>
       <p class="text-blue-textm hover:text-white text-base px-6 pb-6">Block hashes are randomly generated by a <br>decentralized block chain and can be <br>
      queried by anyone, anywhere, anytime</p>
       </div>

</template>
<script>
 export default {
     name: 'Fast',
 }
</script>